services:
  guzzle_client:
    class: GuzzleHttp\Client
    arguments:
      config:
        timeout:   2.0
        base_uri: 'http://staging.wadify.com'

  guzzle_client_sandbox:
    class: GuzzleHttp\Client
    arguments:
      config:
        timeout:   2.0
        base_uri: 'https://sandbox.wadify.com'